// <auto-generated />
using GeoHelper.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GeoHelper.Migrations
{
    [DbContext(typeof(GeoHelperContext))]
    [Migration("20171119173744_Update")]
    partial class Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeoHelper.Models.Point", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<int>("projectId");

                    b.Property<double>("x");

                    b.Property<double>("y");

                    b.Property<double>("z");

                    b.HasKey("ID");

                    b.ToTable("Point");
                });

            modelBuilder.Entity("GeoHelper.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.Property<string>("frameOfReference");

                    b.Property<string>("name");

                    b.Property<string>("owner");

                    b.HasKey("ID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("GeoHelper.Models.UsersProjects", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("leading");

                    b.Property<int>("projectId");

                    b.Property<string>("user");

                    b.HasKey("ID");

                    b.ToTable("UsersProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
